version: '3'
services:

  #MySQL Service
  db:
    image: mysql:5.7.22
    container_name: mysql_condominio
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=condominio
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user 
    volumes:
      - ./dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf

  #PHP Service
  php:
    build:
      context: ./php7.2-fpm
    container_name: php_condominio
    depends_on:
      - db
    command: bash -c "php-fpm  && php-fpm -v"
    volumes:
      - ./src:/var/www/html:rw
      - ./php7.2-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    links:
      - db

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver_nginx
    depends_on:
      - php
    volumes:
      - ./src:/var/www/html
      - ./php7.2-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default:/etc/nginx/conf.d/default.conf
    
volumes:
  mysql-data:
    driver: "local"